Week2 Tarek Aljabr ===> Databases;
HackYourHomework/databases pull request #20
Opened 2021-03-02 19:07 UTC by Tarek666666

2021-03-06 14:51 UTC, unmeshvrije requested changes
Good work. I see that you implemented feedback from last week. Consistent naming.
Please check other comments

2021-03-06 14:51 UTC, unmeshvrije commented on Week2/homework/aggregations.js
> +    `SELECT authors.university, COUNT(research_papers.paper_title) AS total FROM research_papers JOIN papers_details ON research_papers.paper_id = papers_details.paper_id JOIN authors ON authors.auth
What if a paper is written by multiple authors or when two papers have the same title ?

2021-03-06 14:51 UTC, unmeshvrije commented on Week1/exercise2/index.js
> +
This is week 1 exercises. 
Please make sure that the PR only contains the work for week 2

2021-03-06 14:51 UTC, unmeshvrije commented on Week2/homework/Relationships.js
> +const createResearchPaperTable = `CREATE TABLE IF NOT EXISTS research_papers (paper_id INT AUTO_INCREMENT, paper_title VARCHAR(250), conference VARCHAR(250), publish_date DATE, CONSTRAINT pk_research
Nitpick: Please don't use more than 80 characters in one line. It gives better readability.

2021-03-06 14:51 UTC, unmeshvrije commented on Week2/homework/aggregations.js
> +    `SELECT COUNT(paper_title) AS papers_by_female_authors FROM research_papers JOIN papers_details ON papers_details.paper_id = research_papers.paper_id JOIN authors on papers_details.author_no = au
Are you sure COUNT(paper_title)` works in all cases ?

2021-03-06 14:51 UTC, unmeshvrije commented on Week2/homework/joins.js
> +    `SELECT authors.*, research_papers.paper_title FROM authors LEFT JOIN papers_details ON authors.author_no = papers_details.author_no LEFT JOIN research_papers ON papers_details.paper_id = researc
Please indent the query with different keywords on separate line:
```
SELECT authors.*, research_papers.paper_title 
FROM authors 
LEFT JOIN papers_details  ON authors.author_no = papers_details.author_no 
LEFT JOIN research_papers ON papers_details.paper_id = research_papers.paper_id
GROUP BY authors.author_no, research_papers.paper_id;
```

2021-03-06 14:51 UTC, unmeshvrije commented on Week2/homework/keys.js
> +    "CREATE TABLE IF NOT EXISTS authors (author_no INT NOT NULL AUTO_INCREMENT, author_name VARCHAR(55), university VARCHAR(55), date_of_birth DATE, h_index INT, gender ENUM('m','f'), CONSTRAINT pk_a
line too long

2021-03-06 14:51 UTC, unmeshvrije commented on Week2/homework/keys.js
> +    "ALTER TABLE authors ADD mentor INT, ADD CONSTRAINT fk_author FOREIGN KEY (mentor) REFERENCES authors(author_no)"
good!

2021-03-14 17:56 UTC, Tarek666666 commented on Week2/homework/aggregations.js
> +    `SELECT authors.university, COUNT(research_papers.paper_title) AS total FROM research_papers JOIN papers_details ON research_papers.paper_id = papers_details.paper_id JOIN authors ON authors.auth
Yes i think the result won't be correct anymore, so i think i should have used paper_id instead of title. this way if a paper is written by multiple authors or duplicated titles won't be a problem.

2021-03-14 17:58 UTC, Tarek666666 commented on Week1/exercise2/index.js
> +
i forgot to checkout branch week1 before start working on the homework, i paid attention to that in week3 homework. the PR includes only the files from week3.

2021-03-14 18:00 UTC, Tarek666666 commented on Week2/homework/Relationships.js
> +const createResearchPaperTable = `CREATE TABLE IF NOT EXISTS research_papers (paper_id INT AUTO_INCREMENT, paper_title VARCHAR(250), conference VARCHAR(250), publish_date DATE, CONSTRAINT pk_research
Done.

2021-03-14 18:01 UTC, Tarek666666 commented on Week2/homework/aggregations.js
> +    `SELECT COUNT(paper_title) AS papers_by_female_authors FROM research_papers JOIN papers_details ON papers_details.paper_id = research_papers.paper_id JOIN authors on papers_details.author_no = au
No it was not the best choice, you explained it for us in the class.
 it doesn't work in all cases such as duplicated titles. so here also i should have used paper_id instead of titles.

2021-03-14 18:04 UTC, Tarek666666 commented on Week2/homework/joins.js
> +    `SELECT authors.*, research_papers.paper_title FROM authors LEFT JOIN papers_details ON authors.author_no = papers_details.author_no LEFT JOIN research_papers ON papers_details.paper_id = researc
it's really easier to read this way.

2021-03-14 18:05 UTC, Tarek666666 commented on Week2/homework/keys.js
> +    "CREATE TABLE IF NOT EXISTS authors (author_no INT NOT NULL AUTO_INCREMENT, author_name VARCHAR(55), university VARCHAR(55), date_of_birth DATE, h_index INT, gender ENUM('m','f'), CONSTRAINT pk_a
i splitted it out into tow lines.

2021-03-14 18:06 UTC, Tarek666666 commented on Week2/homework/keys.js
> +    "ALTER TABLE authors ADD mentor INT, ADD CONSTRAINT fk_author FOREIGN KEY (mentor) REFERENCES authors(author_no)"
Thanks Unmesh, for your time and your feedback. i do appreciate it .

2021-04-30 08:32 UTC, closed without merging