Ahmad - Week2
HackYourHomework/databases pull request #21
Opened 2021-03-02 19:46 UTC by amagsid

HW for Databases week2

2021-03-06 14:56 UTC, unmeshvrije requested changes
Overall good work. Please check my comments

2021-03-06 14:56 UTC, unmeshvrije commented on Week2/Homework/1.Keys.js
> +  ADD mentor INTEGER,
I love ❤️  the indentation. Makes it much more readable! 🎉

2021-03-06 14:56 UTC, unmeshvrije commented on Week2/Homework/2.Relationships.js
> +    authorNO INT,
perhaps `NOT NULL` ?

2021-03-06 14:56 UTC, unmeshvrije commented on Week2/Homework/2.Relationships.js
> +    SET mentor = CASE
This is a nice trick to update mentors!

2021-03-06 14:56 UTC, unmeshvrije commented on Week2/Homework/2.Relationships.js
> +    authorNO INT,
authorNO is an add name. I would rename it as `author_no` or `author_id`

2021-03-06 14:56 UTC, unmeshvrije commented on Week2/Homework/4.AggrecateFunctions.js
> +    SELECT COUNT(research_papers.paper_title) AS papers_by_female_authors
What is two papers have the same title ?

2021-03-06 14:56 UTC, unmeshvrije commented on Week2/Homework/4.AggrecateFunctions.js
> +    SELECT university, COUNT (research_papers.paper_title) AS research_papers
Same as before: what if two papers have the same title, or multiple people wrote the same paper ?

Did you check if the query covers these cases ?

2021-03-06 15:22 UTC, amagsid commented on Week2/Homework/2.Relationships.js
> +    SET mentor = CASE
This one was my last resort after trying for a couple or so hours 😂

2021-03-06 15:29 UTC, amagsid commented on Week2/Homework/4.AggrecateFunctions.js
> +    SELECT COUNT(research_papers.paper_title) AS papers_by_female_authors
Good catch!

2021-03-06 15:30 UTC, amagsid commented on Week2/Homework/4.AggrecateFunctions.js
> +    SELECT university, COUNT (research_papers.paper_title) AS research_papers
This one slipped by in the sea of errors I was trying to fix getting the HW for this week done 😂

2021-03-07 08:21 UTC, amagsid commented
As always, thanks @unmeshvrije for taking the time. I fixed code according to your comments! 🚀

2021-04-30 08:32 UTC, closed without merging