Homework week 2 SAEED
HackYourHomework/databases pull request #22
Opened 2021-03-02 22:57 UTC by SaeedRafay

2021-03-06 15:00 UTC, unmeshvrije requested changes
good work! Please take a look at some comments

2021-03-06 15:00 UTC, unmeshvrije commented on Week2/relationships.js
> +      author INT,
`NOT NULL` ?

2021-03-16 00:18 UTC, SaeedRafay commented on Week2/aggregate.js
> +    FROM authors_papers AS ap
Thanks 😄

2021-03-16 00:19 UTC, SaeedRafay commented on Week2/aggregate.js
> +    SELECT a.university, COUNT(DISTINCT p.paper_title) AS sum_papers
I have now added `p.paper_id` as well with the title.

2021-03-16 00:19 UTC, SaeedRafay commented on Week2/aggregate.js
> +    SELECT COUNT(DISTINCT p.paper_title) AS total_female_papers
I have now added `p.paper_id` as well with the title.

2021-03-16 00:19 UTC, SaeedRafay commented on Week2/joins.js
> +    LEFT JOIN authors_papers AS ap ON a.author_no = ap.author
That was by mistake

2021-03-16 00:20 UTC, SaeedRafay commented on Week2/relationships.js
> +      author INT,
Added `NOT NULL`. Thanks for notifying.

2021-03-16 00:21 UTC, SaeedRafay commented
Thanks, @unmeshvrije for the amazing videos on databases and QnA session and especially for reviewing my homework.

2021-04-30 08:32 UTC, closed without merging