Marwa-Week1
HackYourHomework/databases pull request #47
Opened 2021-05-05 21:25 UTC by Marwa-kwara

2021-05-08 11:13 UTC, unmeshvrije requested changes
Please make a new PR with changes in files relevant to the homework only.

2021-05-08 11:13 UTC, unmeshvrije commented on README.md
> +Here is [a screenshot of the step](https://i.stack.imgur.com/nFnWV.jpg).
This is not part of the homework!

Can you make a new PR ? with only relevant files for the homework.

To suggest changes in the README / reading material, please make a PR to HackYourFuture repository and not to the HackYourHomework repository !

2021-05-08 14:26 UTC, Marwa-kwara commented on README.md
> +Here is [a screenshot of the step](https://i.stack.imgur.com/nFnWV.jpg).
okay!
I will make a new PR with changes in files relevant to the homework only, BUT should I make it to HackYourFuture repository  not to the HackYourHomework repository?

2021-05-16 07:54 UTC, robvk commented
New one is up

2021-05-16 07:54 UTC, closed without merging