Ehab DB Week1
HackYourHomework/databases pull request #7
Opened 2021-02-23 19:38 UTC by ehabwasel

2021-02-27 14:04 UTC, Breus requested changes
Looks good in general, but besides some small code improvements there is one error in your homework in the first exercise (something with the starting and ending times).

2021-02-27 14:04 UTC, Breus commented on Week1/homework/ex1_create_table.js
> +const create_Meeting  = "create table Meeting (meeting_no int, meeting_title varchar(50),  starting_time date , ending_time date)";
Hint: check via MySQL workbench or terminal what the actual inserted values for starting_time and ending_time are ;-)

2021-02-27 14:04 UTC, Breus commented on Week1/homework/ex2.js
> +var select_query = [
Any reason you used var for this array instead of const?

2021-02-28 10:00 UTC, ehabwasel commented on Week1/homework/ex1_create_table.js
> +  console.log(" DB meetup IS connected..");
Ooh yes. Thanks i changed it when i setup and check my sql and i didn't change it. Thanks i changed it naw and i made new commit for your new advices. Thanks 😊

2021-02-28 10:00 UTC, ehabwasel commented on Week1/homework/ex1_create_table.js
> + const array_meeting = ["INSERT INTO Meeting VALUES (1, 'html', '2020-01-01 10:10:10','2020-01-01 10:10:10')","INSERT INTO Meeting VALUES (2, 'css', '2020-01-01 10:10:10','2020-01-01 10:10:10')","INS
Thanks. I did in the new commit 👍

2021-02-28 10:01 UTC, ehabwasel commented on Week1/homework/ex1_create_table.js
> +function tables(create_query){
Yes indeed i changed its name to create_tables now 😊

2021-02-28 10:02 UTC, ehabwasel commented on Week1/homework/ex1_create_table.js
> +      if (error) {
Yes of course i will use the same style with curly brackets. I updated it with new commit 😉

2021-02-28 10:04 UTC, ehabwasel commented on Week1/homework/ex2.js
> +var select_query = [
This really mistake in new commit i used const to avoid variable pollution

2021-04-30 08:32 UTC, closed without merging